name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 PM UTC (you can adjust the time)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Add a commit with your email in the name
    - name: Commit changes with email 21f3000311@ds.study.iitm.ac.in
      run: |
        echo "This is a daily commit" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit by 21f3000311@ds.study.iitm.ac.in"
        git push
      env:
        GIT_AUTHOR_NAME: "GitHub Action"
        GIT_AUTHOR_EMAIL: "21f3000311@ds.study.iitm.ac.in"
        GIT_COMMITTER_NAME: "GitHub Action"
        GIT_COMMITTER_EMAIL: "21f3000311@ds.study.iitm.ac.in"
